import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Breadcrumb from "./Breadcrumb";
import Footer from "./Footer";
import Header from "./Header";
import MobileMenu from "./MobileMenu";

const Layout = ({
    children,
    parent,
    sub,
    subChild,
    noBreadcrumb,
    headerStyle,
}) => {
    const [isToggled, setToggled] = useState(false);
    const [pageTitle, setPageTitle] = useState('SpiceeUpp');
    const router = useRouter();
    const toggleClick = () => {
        setToggled(!isToggled);
        isToggled
            ? document
                  .querySelector("body")
                  .classList.remove("mobile-menu-active")
            : document
                  .querySelector("body")
                  .classList.add("mobile-menu-active");
    };

    useEffect(() => {
        const routeName = router.pathname.split("/").filter(Boolean).pop(); // Get the last part of the route
        const title = routeName ? `${routeName} | ${pageTitle}` : pageTitle;
        setPageTitle(title);
    }, [router.pathname]);

    return (
        <>
            <Head>
            <title>{`E-commerce | ${pageTitle}`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {isToggled && <div className="body-overlay-1" onClick={toggleClick}></div>}

            <Header headerStyle={headerStyle} isToggled={isToggled} toggleClick={toggleClick} />
            <MobileMenu isToggled={isToggled} toggleClick={toggleClick} />
            <main className="main">
                <Breadcrumb parent={parent} sub={sub} subChild={subChild} noBreadcrumb={noBreadcrumb} />
                {children}
            </main>
            <Footer />
        </>
    );
};

export default Layout;
